FROM --platform=$BUILDPLATFORM docker.io/ollama/ollama:latest

# RUN bash -c '                             \
#     ( ollama serve ) & serverpid="$!";    \
#     sleep 5;                              \
#     ollama pull orca-mini &&                    \
#     kill "$serverpid" &&                  \
#     wait "$serverpid"                     \
# '
