name: Commit Stage

on:
  push:
  schedule: # Every Monday
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  publish:
    name: Publsh
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/multi-arch-publish.yml
    strategy:
      fail-fast: false
      matrix:
        project: [
          {context: ollama/llama2, image: ollama-llama2},
          {context: ollama/llava, image: ollama-llava},
          {context: ollama/mistral, image: ollama-mistral},
          {context: ollama/orca-mini, image: ollama-orca-mini},
          {context: ollama/phi, image: ollama-phi}
        ]
    with:
      context: ${{ matrix.project.context }}
      image: ${{ matrix.project.image }}   
    secrets:  
      push-token: ${{ secrets.IMAGE_PUSH_TOKEN }}
