name: Commit Stage

on:
  push:
  schedule: # Every Monday
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  build-and-publish:
    name: Build and Publsh
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-and-publish.yml
    strategy:
      fail-fast: false
      matrix:
        project: [
          {context: ollama/llama2, image: ollama-llama2},
          {context: ollama/mistral, image: ollama-mistral},
          {context: ollama/orca-mini, image: ollama-orca-mini},
          {context: ollama/phi, image: ollama-phi}
        ]
    with:
      context: ${{ matrix.project.context }}
      image: ${{ matrix.project.image }}    
