name: Commit Stage

on:
  push:
    paths-ignore:
      - '.editorconfig'
      - '.gitignore'
      - '*.adoc'
      - '*.png'
      - '*.md'
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/*.md'
      - '.github/*.yml'
      - '.github/*.yaml'
  schedule: # Every Monday
    - cron: '0 0 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    name: Publish
    permissions:
      actions: read
      contents: read
      id-token: write
      packages: write
    uses: ./.github/workflows/multi-arch-publish.yml
    strategy:
      fail-fast: false
      matrix:
        project: [
          {context: ollama/aya, image: ollama-aya},
          {context: ollama/gemma2, image: ollama-gemma2},
          {context: ollama/llama3.2, image: ollama-llama3-2},
          {context: ollama/llava, image: ollama-llava},
          {context: ollama/mistral, image: ollama-mistral},
          {context: ollama/moondream, image: ollama-moondream},
          {context: ollama/nomic-embed-text, image: ollama-nomic-embed-text},
          {context: ollama/phi3.5, image: ollama-phi3-5},
        ]
    with:
      context: ${{ matrix.project.context }}
      image: ${{ matrix.project.image }}
    secrets:  
      push-token: ${{ secrets.IMAGE_PUSH_TOKEN }}
