name: Commit Stage

on:
  push:
  schedule: # Every Monday
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  publish:
    name: Publish
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
    uses: ./.github/workflows/multi-arch-publish.yml
    strategy:
      fail-fast: false
      matrix:
        project: [
          {context: ollama/aya, image: ollama-aya},
          {context: ollama/bakllava, image: ollama-bakllava},
          {context: ollama/gemma2, image: ollama-gemma2},
          {context: ollama/llama3.1, image: ollama-llama3-1},
          {context: ollama/llava, image: ollama-llava},
          {context: ollama/mistral, image: ollama-mistral},
          {context: ollama/mistral-nemo, image: ollama-mistral-nemo},
          {context: ollama/moondream, image: ollama-moondream},
          {context: ollama/mxbai-embed-large, image: ollama-mxbai-embed-large},
          {context: ollama/nomic-embed-text, image: ollama-nomic-embed-text},
          {context: ollama/orca-mini, image: ollama-orca-mini},
        ]
    with:
      context: ${{ matrix.project.context }}
      image: ${{ matrix.project.image }}
    secrets:  
      push-token: ${{ secrets.IMAGE_PUSH_TOKEN }}
